### ISSUE TITLE
Algorithm impala cannot use GPU[ALTER]

### ISSUE THREAD

**Issue by HouSo1in** [iffiX/machin#2]
**machin/frame/algorithms/impala.py, line 363, 373**

`vs[idx] = (value[idx] + delta_v[idx] +
                               self.discount * c[idx] *
                               (vs[idx + 1] - value[idx + 1]))`

This should be corrected to the following code

`vs[idx] = (value[idx].to('cpu') + delta_v[idx] +
                               self.discount * c[idx] *
                               (vs[idx + 1] - value[idx + 1].to('cpu')))`

Do the same for line 373

**Comment by iffiX** [comment]
Fixing the problem, currently I am restructuring my test suite to support GPU testing.

**Comment by iffiX** [comment]
OK, problem should have been fixed, now merge to release branch and push as a new version:
https://github.com/iffiX/machin/commit/5fca74e733962c28e3190b60f8b79fbbe18a0aaf
