### ISSUE TITLE
Apex-ddpg cannot use GPU

### ISSUE THREAD

**Issue by swd543** [iffiX/machin#25]
Apex-ddpg cannot use the GPU. The tests in the apex-ddpg seem to all be using the CPU, is this feature currently not supported? I tried changing the actor and critic network in [ddpg_apex.py](machin/test/frame/algorithms/test_apex.py) to use cuda:0 but I get the following error. I tried using the default example and also world size=2, 1 worker and 1 sampler to resolve any self-deadlocks being caused by the multiple processes.

```
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by swd543** [comment]
Update - my gpu is in exclusive mode in `nvidia-smi` and I cannot change the setting due to privileges. Is there another way to run the code?

**Comment by iffiX** [comment]
Because your GPU is in **exclusive mode**, which means only one process can occupy the GPU, then you should move the model to a unique GPU every time you create a new process. Eg: cuda:0 for process with rank 0, cuda:1 for process with rank 1. There is no way to work around this.
