### ISSUE TITLE
[FEATURE] Custom replay buffers

### ISSUE THREAD

**Issue by Bobingstern** [iffiX/machin#28]
Sparse rewards are a problem for everyone in RL dealing with robotics and such.
Just like its possible to create your own networks (which is awesome), I think it could be useful be able to create your own replay buffers to implement things like Hindsight Experience Replay and others.

**Comment by iffiX** [comment]
Hi, this framework is designed to be customizable for all parts, including the buffer, just implement your own buffer by inheriting the `Buffer` class in https://github.com/iffiX/machin/blob/master/machin/frame/buffers/buffer.py
And pass the buffer to whichever "TorchFramework" you would like to plug in through its init arguments, take A2C as an example:
https://github.com/iffiX/machin/blob/7fa986b1bafdefff117d6ff73d14644a5488de9d/machin/frame/algorithms/a2c.py#L51

Currently I don't have time to provide the HER implementation myself, however I can provide any technical support you need.
