### ISSUE TITLE
[ALTER] Readability - black standard formatting

### ISSUE THREAD

**Issue by ikamensh** [iffiX/machin#9]
**Where to alter**
It's best to alter throughout the entire library, but my specific pain started with `ppo.py`.

**Why to alter**
* Custom formatting is less readable than standard black formatting.
* Standard formatting means minimal diffs on any future edits - easier to review

**How to alter**
1. Run black https://github.com/psf/black on entire repository
2. [OPTIONAL] add this commit to list of ignored commits for git blame as described here https://akrabat.com/ignoring-revisions-with-git-blame/ - I think this can be skipped because so far you are the main author of the library and git history is not that rich.
3. [OPTIONAL] add pre-commit hook to run black on all future commits automatically https://black.readthedocs.io/en/stable/version_control_integration.html

Example: originally, this is how code looks that I needed to debug:
```
            batch_size, (state, action, advantage) = \
                self.replay_buffer.sample_batch(self.batch_size,
                                                sample_method="random_unique",
                                                concatenate=concatenate_samples,
                                                sample_attrs=[
                                                    "state", "action", "gae"],
                                                additional_concat_attrs=[
                                                    "gae"
                                                ])
```
- that's a festival of different indentation levels.

Here is how it looks after `black` reformatting:

```
            batch_size, (state, target_value) = self.replay_buffer.sample_batch(
                self.batch_size,
                sample_method="random_unique",
                concatenate=concatenate_samples,
                sample_attrs=["state", "value"],
                additional_concat_attrs=["value"],
            )
```

**Comment by ikamensh** [comment]
Hi, thanks for this library! Let me know if you'd like me to create this change via PR / if you'd like the pre-commit hook.

**Comment by iffiX** [comment]
Love all of your suggestions, including optional ones. If you can create a PR, that would be great. I will look into these methods in detail after finishing the auto launcher :)

**Comment by ikamensh** [comment]
All proposals were implemented.

**Comment by iffiX** [comment]
Thank you for your contribution @ikamensh :)
